version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mock-tools-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mock_tools_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mock_tools}
      MYSQL_USER: ${MYSQL_USER:-mock_tools_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mock_tools_password}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - mock-tools-network-prod
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Mock Tools 应用
  app:
    image: zhaozhuodev/mock_tools:latest
    container_name: mock-tools-app-prod
    restart: unless-stopped
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER:-mock_tools_user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-mock_tools_password}
      DB_DATABASE: ${MYSQL_DATABASE:-mock_tools}
      JWT_SECRET: ${JWT_SECRET:-mock_tools_jwt_secret_production}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mock-tools-network-prod
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Nginx 反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: mock-tools-nginx-prod
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - mock-tools-network-prod
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'

volumes:
  mysql_data_prod:

networks:
  mock-tools-network-prod:
    driver: bridge
